# Generated by Django 5.2.8 on 2025-12-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplocation',
            name='tailor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.tailorprofile'),
        ),
        migrations.AddField(
            model_name='tailorservice',
            name='tailor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.tailorprofile'),
        ),
    ]
