# Generated by Django 6.0 on 2025-12-08 12:56

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0003_alter_shoplocation_id_alter_tailorservice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplocation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shoplocation',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='shoplocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoplocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
