# Generated by Django 6.0 on 2025-12-08 13:06

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0004_shoplocation_city_shoplocation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplocation',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='-7.9666204,112.6326321', max_length=63, null=True),
        ),
    ]
