# Generated by Django 6.0 on 2025-12-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='snap_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
